[package]
name = "dbusserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.9.7"
dbus-tree = "0.9.2"
tokio = { version = "1.36.0", features = ["full"] }